[package]
name = "async_example"
version = "0.1.0"
authors = ["andy <andysalerno@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
runtime = "0.3.0-alpha.6"
rand = "0.7.0"
